### ISSUE TITLE
Express로 진행한 프로젝트 작업 이전하기

### ISSUE THREAD

**Issue by engulfedInFlames** [engulfedInFlames/yourfan-react-frontend#2]
## ✅ 작업 내용
- 웹사이트 디자인 이전
- 백과의 데이터 통신을 위한 준비 완료하기

**Comment by vishalpawarR** [comment]
@engulfedInFlames if you can explain the issue or point to the specific issue with proper guide may be I can try to fix this issue

**Comment by engulfedInFlames** [comment]
> @engulfedInFlames if you can explain the issue or point to the specific issue with proper guide may be I can try to fix this issue

I really appreciate your interest in my project.
Unfortunately, this is not my personal project, but rather a project that will be judged in a boot camp I'm participating in. Hence, participation by others who are not team members is limited.
Again, thank you for your interest in my project.
